export const PARUL_LOCATIONS = [
  { code: 'A1', category: 'Academic', name: 'Parul Institute of Engineering & Technology' },
  { code: 'A2', category: 'Academic', name: 'Parul Institute of Engineering & Technology (Diploma Studies)' },
  { code: 'A3', category: 'Academic', name: 'Parul Institute of Engineering & Technology' },
  { code: 'A4', category: 'Academic', name: 'Parul Institute of Pharmacy' },
  { code: 'A5', category: 'Academic', name: 'Parul Institute of Engineering & Technology' },
  { code: 'A6', category: 'Academic', name: 'Parul Institute of Nursing' },
  { code: 'A7', category: 'Academic', name: 'Jawaharlal Nehru Homoeopathic Medical College' },
  { code: 'A8', category: 'Academic', name: 'Parul Institute of Pharmacy & Research' },
  { code: 'A9', category: 'Academic', name: 'Parul Polytechnic Institute' },
  { code: 'A10', category: 'Academic', name: 'School of Pharmacy' },
  { code: 'A11', category: 'Academic', name: 'Medical Library & Insights Centre' },
  { code: 'A12', category: 'Academic', name: 'Medical Sciences & Research Institute' },
  { code: 'A13', category: 'Academic', name: 'Parul Institute of Ayurveda' },
  { code: 'A14', category: 'Academic', name: 'Parul Institute of Business Administration' },
  { code: 'A15', category: 'Academic', name: 'Faculty of Management Studies' },
  { code: 'A16', category: 'Academic', name: 'Parul Institute of Architecture & Research' },
  { code: 'A17', category: 'Academic', name: 'Parul Institute of Homoeopathy & Research' },
  { code: 'A18', category: 'Academic', name: 'Parul Institute of Ayurveda & Research' },
  { code: 'A19', category: 'Academic', name: 'Parul Institute of Technology & Hotel Management' },
  { code: 'A20', category: 'Academic', name: 'Engineering Workshop' },
  { code: 'A21', category: 'Academic', name: 'Parul Institute of Applied Sciences & Research' },
  { code: 'A22', category: 'Academic', name: 'Parul Institute of Design' },
  { code: 'A23', category: 'Academic', name: 'Parul Institute of Performing Arts' },
  { code: 'A24', category: 'Academic', name: 'Bhagat Singh Bhawan' },
  { code: 'A25', category: 'Academic', name: 'C.V. Raman Centre' },
  { code: 'A26', category: 'Academic', name: '24 Frames Studio' },
  { code: 'C1', category: 'Administrative', name: 'Student Section' },
  { code: 'C2', category: 'Administrative', name: 'Admission Cell' },
  { code: 'C3', category: 'Administrative', name: 'Centre for International Relations' },
  { code: 'C4', category: 'Administrative', name: 'HR & Administration' },
  { code: 'C5', category: 'Administrative', name: 'Industry Collaborations & Placement Cell' },
  { code: 'E1', category: 'Hospital', name: 'Parul Ayurveda Hospital' },
  { code: 'E2', category: 'Hospital', name: 'Parul Sevashram Hospital' },
  { code: 'E3', category: 'Hospital', name: 'Khanderao Ayurved Hospital' },
  { code: 'E4', category: 'Hospital', name: 'Parul Institute of Homoeopathy Hospital' },
  { code: 'E5', category: 'Hospital', name: 'Jawaharlal Nehru Homoeopathic Medical College Hospital' },
  { code: 'B1', category: 'Bank', name: 'Central Bank of India' },
  { code: 'TS', category: 'Transport', name: 'Transport Office' },
  { code: 'P1', category: 'Parking', name: 'Visitor Parking' },
  { code: 'P2', category: 'Parking', name: 'Staff 2-Wheeler Parking' },
  { code: 'P3', category: 'Parking', name: 'Student Parking' },
  { code: 'P4', category: 'Parking', name: 'Bus Parking' },
  { code: 'P5', category: 'Parking', name: 'Staff Parking' },
  { code: 'P6', category: 'Parking', name: 'Staff 2-Wheeler Parking' },
  { code: 'P7', category: 'Parking', name: 'Staff 4-Wheeler Parking' },
  { code: 'P8', category: 'Parking', name: 'Staff 4-Wheeler Parking' },
  { code: 'G1', category: 'Sports Ground', name: 'Watcher\'s Park' },
  { code: 'G3', category: 'Sports Ground', name: 'Multi-Purpose Football Ground' },
  { code: 'G5', category: 'Sports Ground', name: 'Cricket Ground' },
  { code: 'G6', category: 'Sports Ground', name: 'Open Ground' },
  { code: 'G7', category: 'Sports Ground', name: 'Multi-Purpose Ground' },
  { code: 'G9', category: 'Sports Ground', name: 'Court Area' },
  { code: 'G10', category: 'Sports Ground', name: 'Court Area Extension' },
  { code: 'H1', category: 'Hostel', name: 'Shastri Bhawan A' },
  { code: 'H2', category: 'Hostel', name: 'Shastri Bhawan B' },
  { code: 'H3', category: 'Hostel', name: 'Shastri Bhawan C' },
  { code: 'H4', category: 'Hostel', name: 'Marie Curie Residence' },
  { code: 'H5', category: 'Hostel', name: 'Sarojini Bhawan A' },
  { code: 'H6', category: 'Hostel', name: 'Sarojini Bhawan B' },
  { code: 'H7', category: 'Hostel', name: 'Sarojini Bhawan C' },
  { code: 'H8', category: 'Hostel', name: 'Indira Bhawan A' },
  { code: 'H9', category: 'Hostel', name: 'Indira Bhawan B' },
  { code: 'H10', category: 'Hostel', name: 'Indira Bhawan C' },
  { code: 'H11', category: 'Hostel', name: 'Albert Einstein Residence' },
  { code: 'H12', category: 'Hostel', name: 'Kalam Bhawan A' },
  { code: 'H13', category: 'Hostel', name: 'Kalam Bhawan B' },
  { code: 'H14', category: 'Hostel', name: 'Kalam Bhawan C' },
  { code: 'H15', category: 'Hostel', name: 'Tagore Bhawan A' },
  { code: 'H16', category: 'Hostel', name: 'Tagore Bhawan B' },
  { code: 'H17', category: 'Hostel', name: 'Dhyan Bhawan' },
  { code: 'H18', category: 'Hostel', name: 'Janki Bhawan' },
  { code: 'H19', category: 'Hostel', name: 'Teresa Bhawan A' },
  { code: 'H20', category: 'Hostel', name: 'Teresa Bhawan B' },
  { code: 'H21', category: 'Hostel', name: 'Teresa Bhawan C' },
  { code: 'H22', category: 'Hostel', name: 'Teresa Bhawan D' },
  { code: 'H23', category: 'Hostel', name: 'Hostel Block' },
  { code: 'H24', category: 'Hostel', name: 'Hostel Block' },
  { code: 'H25', category: 'Hostel', name: 'Atal Bhawan A' },
  { code: 'H26', category: 'Hostel', name: 'Atal Bhawan B' },
  { code: 'H27', category: 'Hostel', name: 'Milka Bhawan A' },
  { code: 'H28', category: 'Hostel', name: 'Kalpana Bhawan A' },
  { code: 'H29', category: 'Hostel', name: 'Kalpana Bhawan B' },
  { code: 'H30', category: 'Hostel', name: 'Sardar Bhawan A' },
  { code: 'H31', category: 'Hostel', name: 'Sardar Bhawan B' },
  { code: 'H32', category: 'Hostel', name: 'Atal Bhawan D' },
  { code: 'H33', category: 'Hostel', name: 'Azad Bhawan A' },
  { code: 'H34', category: 'Hostel', name: 'Hostel Block' },
  { code: 'F1', category: 'Food Court', name: 'Food Court' },
  { code: 'F2', category: 'Food Court', name: 'Food Court' },
  { code: 'F3', category: 'Food Court', name: 'Food Court' },
  { code: 'F4', category: 'Food Court', name: 'Food Court' },
  { code: 'F5', category: 'Food Court', name: 'Food Court' },
  { code: 'F6', category: 'Food Court', name: 'Food Court' },
  { code: 'F7', category: 'Food Court', name: 'Food Court' },
  { code: 'F8', category: 'Food Court', name: 'Food Court' },
  { code: 'Q1', category: 'Staff Quarters', name: 'Staff Quarter' },
  { code: 'Q2', category: 'Staff Quarters', name: 'Staff Quarter' },
  { code: 'Q3', category: 'Staff Quarters', name: 'Staff Quarter' },
  { code: 'Q4', category: 'Staff Quarters', name: 'Staff Quarter' },
  { code: 'Q5', category: 'Staff Quarters', name: 'Staff Quarter' },
  { code: 'Q6', category: 'Staff Quarters', name: 'Staff Quarter' },
  { code: 'S1', category: 'Swimming Pool', name: 'Swimming Pool' },
  { code: 'T', category: 'Temple', name: 'Temple' },
  { code: 'STP', category: 'Utility', name: 'Sewage Treatment Plant' },
  { code: 'PU_ARENA', category: 'Sports Facility', name: 'PU Equestrian Horse Riding Arena' }
];

export const CATEGORIZED_LOCATIONS = PARUL_LOCATIONS.reduce((acc, loc) => {
  if (!acc[loc.category]) acc[loc.category] = [];
  acc[loc.category].push(loc);
  return acc;
}, {});
